language: rust

cache: cargo

before_script:
  - apt install xorg-dev
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test

