language: rust

cache: cargo

addons:
  apt:
    packages:
      - xorg-dev
      
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test

