language: rust

cache: cargo

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
  - rustc --version
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test

