language: rust

cache: cargo

addons:
  apt:
    packages:
      - xorg-dev
      - libasound2-dev
      
before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test

