[package]
name = "carambolage"
version = "0.1.0"
authors = [
    "Fabian Drinck <fabian.drinck@rwth-aachen.de>",
    "Stephan Schauerte <stephan@schauerte.online>"
]

[dependencies]
nalgebra = "~0.16.4"
time = "~0.1.40"
rand = "~0.5"
gl = "0.10.0"
glfw = "~0.24.0"

[profile.release]
lto = true
