[package]
name = "carambolage"
version = "0.1.0"
authors = [
    "Fabian Drinck <fabian.drinck@rwth-aachen.de>",
    "Stephan Schauerte <stephan@schauerte.online>"
]

[dependencies]
glium = "*"
nalgebra = "~0.16.1"
time = "~0.1.40"

[profile.release]
lto = true
