[package]
name = "carambolage"
version = "0.1.0"
authors = [
    "Fabian Drinck <fabian.drinck@rwth-aachen.de>",
    "Stephan Schauerte <stephan@schauerte.online>"
]

[dependencies]
glium = "~0.22.0"
nalgebra = "~0.16.1"
time = "~0.1.40"
rand = "~0.5"

[profile.release]
lto = true
